"""create video_requests table

Revision ID: ce36170aeee8
Revises: 
Create Date: 2026-09-24 18:45:32.252565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce36170aeee8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('video_plan_title', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('reuse_score', sa.Integer(), nullable=False),
    sa.Column('new_generation_required', sa.Integer(), nullable=False),
    sa.Column('provider_generation_cost', sa.Float(), nullable=False),
    sa.Column('internal_processing_cost', sa.Float(), nullable=False),
    sa.Column('estimated_total', sa.Float(), nullable=False),
    sa.Column('estimated_cost_without_reuse', sa.Float(), nullable=False),
    sa.Column('rag_saving_amount', sa.Float(), nullable=False),
    sa.Column('rag_saving_percentage', sa.Integer(), nullable=False),
    sa.Column('reuse_breakdown', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_requests')
    # ### end Alembic commands ###
